### ISSUE TITLE
Qt6 compatibility (5.0 branch)

### ISSUE THREAD

**Issue by arabine** [Dax89/QHexEdit#73]
Hi,

Seems that the 5.0 branch is not compatible with Qt6. I would suggest to keep the legacy version (master) compatible with Qt5 and start the 5.0 branch with a full Qt6 compatiblity.

What do you think?

(for the moment, I removed the StringRefs but there are still multiple warnings regarding QVariant deprecated types).

**Comment by Dax89** [comment]
Hi!
There is a huge thread about 5.0 development (which is almost finalized): https://github.com/Dax89/QHexView/issues/71

I want to keep that branch compatible with both Qt versions, if possible.

**Comment by arabine** [comment]
Saw your changes, you can close this issue, thanks!
