### ISSUE TITLE
Crash in search dialog

### ISSUE THREAD

**Issue by diegoiast** [Dax89/QHexEdit#82]
To reproduce:

1. Search for an int, lest say 100
2. Change the search to "hex".
3. Switch back to searching ints.
4. Boom.

Code crashes here:
https://github.com/Dax89/QHexView/blob/5.0/dialogs/hexfinddialog.cpp#L161

Looks like some issue with the widgets generated for searching integers. I tried adding parents to all widgets there - without success.

**Comment by Dax89** [comment]
Fixed in https://github.com/Dax89/QHexView/commit/f73a72f0e4aad0aa4faf9881579dcb0b9e2ad785

Let me know if it works in your side too!

**Comment by diegoiast** [comment]
Confirmed. Some UI/UX is needed on the dialogs (progress and busy indicator might be in place). I will see if I can contribute something here.
