### ISSUE TITLE
is modified? 

### ISSUE THREAD

**Issue by diegoiast** [Dax89/QHexEdit#84]
I am looking for a way to know if the document has been modified, and then prompt the user to save it.

I saw no API for it. I tried "document()->canUndo()" - but this returns true even when loading a document, and doing nothing. Any ideas? I tried adding this to `QHexDocument()` which just crashed my app:
```c++
bool isModified() const { m_undostack.isClean(); }
```

EDIT:
The `canUndo()` issue is a bug in my part. We can ignore it.

**Comment by Dax89** [comment]
There is no problem to can add `isModified()` along with its signal.

`document()->canUndo()` should return false after a document is loaded, how are you loading data?

**Comment by Dax89** [comment]
`isModified()`, `clearModified()` and `modifiedChanged()` signal added in both `QHexDocument` and `QHexView`
