### ISSUE TITLE
cmake behaviour Qt5 vs Qt6

### ISSUE THREAD

**Issue by audetto** [Dax89/QHexEdit#85]
The recent change to the way this library is used has an odd behaviour.

https://github.com/Dax89/QHexView/blob/40f40f5d6a546646904c094ebefc8216067ab586/CMakeLists.txt#L5

This tries to load Qt6 and falls back to Qt5.
The problem is that it leaves no option to the parent cmake to decide which one to use.

I have a project which I have not ported (yet) to Qt5, so I only build with Qt5. If the user has Qt6, `QHexView` will attempt to use it.

Should there be a way to tell `QHexView` which version of Qt to use? And only use that one?

**Comment by Dax89** [comment]
I have added QHEXVIEW_USE_QT5 option in cmake so you can switch manually to Qt5 and bypass autodetection!

Let me know if it works.

**Comment by audetto** [comment]
thanks
