### ISSUE TITLE
Fixed-width layout for QHexEdit?

### ISSUE THREAD

**Issue by bweir** [Dax89/QHexEdit#9]
Hi there,

I've been fiddling with this widget for a few hours now, and I'm finding it exceptionally difficult to get the layout to behave the way I'd like it to.

A widget like this should really be fixed-width, but it's not, so I'm trying to make it so. However, because the width is set programmatically, and inside QHexEdit there's another QHexEditPrivate so all the size()/sizeHint() commands report the size of the window and not the minimum size their layout, so I'm pretty stumped.

I'm trying to create a viewer that has a fixed width (the width of the text) and a variable height that I can drop into another application. Is there an easy way I can achieve this?

Thanks in advance,

**Comment by bweir** [comment]
If you're curious about what I'm trying to do, have a looksee! I'm using QHexEdit as the basis for a memory map view in a development tool I'm working on called PropellerIDE! =P

This is what I have so far.
![](https://lamestation.atlassian.net/secure/attachment/10902/memorymap_017.png)

This is what I want it to look like but I resized it manually instead of it popping up like this on start up. >.>

**Comment by Dax89** [comment]
Hi!
I'm not sure to understand your question, do you want that the QHexEdit sets its minimum width equal to address_area + hex_area + ascii_area automatically?

**Comment by bweir** [comment]
Yes, and then provide a way to fix the layout at that width, and update it if I were to, say, update the font in the future.

**Comment by Dax89** [comment]
QHexEdit update its metrics in QHexEditPrivate::adjust() method, so, emitting a signal inside of it should do the trick:

In your case you'll need to add some code:
```
/* qhexeditprivate.h */
signals: 
  void minimumWidthChanged(int minwidth);

/* In qhexeditprivate.cpp */
void QHexEditPrivate::adjust()
{
  ...

  /* Add a little padding and take care of VScrollBar's width */
  int minwidth = this->_xPosend + this->_charwidth + this->_vscrollbar->sizeHint().width();
  emit minimumWidthChanged(minwidth); /* Notify that the minimum width is changed */

  if(this->_hexeditdata)
  {
        ....
  }

  ...
}

/* Declare another signal in qhexedit.h */
signals: 
  void minimumWidthChanged(int minwidth);

/* qhexedit.cpp: Forward QHexEditPrivate's signal */
QHexEdit::QHexEdit(QWidget *parent): QFrame(parent)
{
    connect(this->_hexedit_p, SIGNAL(minimumWidthChanged(int)), this, SIGNAL(minimumWidthChanged(int)));
}
```
Finally, you can handle it in your MainWindow, for example

```
/* In mainwindow.h */
private slots:
  void fixWidth(int minwidth);

/* In mainwindow.cpp */
MainWindow::MainWindow(QWidget *parent)
{ 
  connect(ui->hexEdit, SIGNAL(minimumWidthChanged(int)), this, SLOT(fixWidth(int)));
}

void MainWindow::fixWidth(int minwidth)
{
  this->setFixedWidth(minx);
}
```

**Comment by bweir** [comment]
Hey! That did the trick! Thanks!
